name: Build

on:
  push:
    branches:  [main]
  pull_request:
    branches:  [main]
jobs:
  build:
    name : test
    strategy:
      fail-fast: false
      matrix:
       rust : [stable , beta , nightly]
       os : [ ubuntu-latest, macos-latest, windows-latest] 
       include: 
           - os: ubuntu-latest
             rust: nightly
             allow_failure: true
           - os : macOS-latest
             rust: nightly
             allow_failure: true
           - os : windows-latest
             rust: nightly
             allow_failure: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-  
      - run : |
            cargo fmt --all -- --check
            cargo clippy --all --tests -- --deny=warnings
            set RUSTFLAGS="-D warnings"
            cargo build --verbose
            cargo test --verbose   
      - name: if condition
        if: ${{ matrix.rust == 'nightly' }}
        run : |
            rustup override set nightly
            cargo bench -- --nocapture
      - name: before deploy 
        run: |
          cargo doc
          cargo package
